export const NEW_COMPROMISSO = 'NEW_COMPROMISSO';
export const UPDATE_COMPROMISSO = 'UPDATE_COMPROMISSO';
export const DELETE_COMPROMISSO = 'DELETE_COMPROMISSO';
export const LOGIN_ESPECIAL = 'LOGIN_ESPECIAL';
export const GET_DADOS = 'GET_DADOS';